eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:123@server1:8089/eureka/ #,http://admin:123@server2:8082/eureka/
server:
  port: 8083
  servlet:
    context-path: /memeber

spring:
#服务名称
  application:
    name: service-memeber
  zipkin:
    base-url: http://localhost:9001
  sleuth:
      sampler:
        probability: 1

swagger:
  base-package: com.springcloudservice.servicememeber.controller
  title: "会员服务"
  description: "只有会员专用"
